### ISSUE TITLE
Error while converting PointCloud to Laser scan

### ISSUE THREAD

**Issue by jazibdawre** [fictionlab/erc_sim_ws#2]
I was trying to run gmapping on the new marsyard, when I try to convert  the pointcloud to laserscan with a `target_frame` defined this error pops up
```
Transform failure: Invalid argument "/zed2_left_camera_optical_frame" passed to lookupTransform argument source_frame in tf2 frame_ids cannot start with a '/' like  
```
I also tried it while keeping the laser scan in the pointcloud frame, then the laserscan is published however this error comes up while gmapping
```
Laser has to be mounted planar! Z-coordinate has to be 1 or -1. , but gave: -0.485...(more digits)
```

I am using the leo_navigation package which was provided in the earlier repository

**Comment by bjsowa** [comment]
The messages should not be published with a `frame_id` containing a leading `/`. Thanks for noticing the problem. I think, I fixed it now. Could you update and try again?

**Comment by jazibdawre** [comment]
Yup it's working! Thanks
